title: Rami Blog
author: Rami Alzahrani
email: ra-mi@hotmailcom
description: this is my blog and everything.
# social links
twitter_username: rami_m_z
github_username:  ramimalzahrani

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
